const test = require('node:test');
const assert = require('node:assert/strict');
const { processNewPatientStep, parseBirthDate } = require('../../src/services/whatsappNewPatient.service');
const { CONVERSATION_STEPS } = require('../../src/models/WhatsappConversacion');
const now = new Date('2026-08-22T12:00:00Z');
const tx = { LOCK: { UPDATE: 'UPDATE' } }; const activity = { ultimo_mensaje_en: now, expira_en: new Date('2026-08-22T12:30:00Z') };
const item = (data) => ({ telefono: '59177712345', paso_actual: CONVERSATION_STEPS.WAITING_NEW_PATIENT_CONFIRMATION, contexto: { new_patient: data }, async update(value) { Object.assign(this, value); return this; } });
const run = (conversation, message, models) => processNewPatientStep({ conversation, message, transaction: tx, activity, now, models });
const adult = { flow_type: 'SELF', patient_name: 'Ana Perez', birth_date: '1990-04-12', birth_date_display: '12/04/1990', age: 36, minor: false };
const minor = { flow_type: 'OTHER', patient_name: 'Pedro Perez', birth_date: '2016-04-12', birth_date_display: '12/04/2016', age: 10, minor: true, guardian_name: 'Juan Perez', relationship: 'PADRE', legal_guardian: true };

test('fecha calcula minoría y valida calendario', () => { assert.equal(parseBirthDate('12/04/2016', now).minor, true); assert.equal(parseBirthDate('12/04/1990', now).minor, false); assert.equal(parseBirthDate('31/02/2020', now), null); });
test('adulto para mí usa teléfono y selecciona contexto', async () => { const created = []; const conversation = item(adult); const result = await run(conversation, '1', { patientModel: { findAll: async () => [], create: async (data) => { created.push(data); return { id: 10, ...data }; } } }); assert.equal(created[0].telefono, '59177712345'); assert.equal(conversation.paciente_contexto_id, 10); assert.equal(result.responseKind, 'NEW_PATIENT_CREATED'); });
test('menor usa teléfono nulo y crea tutor/relación', async () => { const patients = []; const contacts = []; const relations = []; const conversation = item(minor); await run(conversation, '1', { patientModel: { findAll: async () => [], findOne: async () => ({ id: 20 }), create: async (data) => { patients.push(data); return { id: 35, ...data }; } }, contactModel: { findAll: async () => [], create: async (data) => { contacts.push(data); return { id: 9, ...data }; } }, relationModel: { create: async (data) => relations.push(data) } }); assert.equal(patients[0].telefono, null); assert.equal(patients[0].telefono_normalizado, null); assert.equal(contacts[0].paciente_id, 20); assert.equal(relations[0].contacto_id, 9); assert.equal(relations[0].autoriza_whatsapp, true); assert.equal(relations[0].puede_gestionar_citas, true); });
test('reutiliza tutor único y rechaza teléfono ambiguo', async () => { let contactCreates = 0; const conversation = item(minor); await run(conversation, '1', { patientModel: { findAll: async () => [], create: async (data) => ({ id: 35, ...data }) }, contactModel: { findAll: async () => [{ id: 7 }], create: async () => { contactCreates++; } }, relationModel: { create: async () => ({}) } }); assert.equal(contactCreates, 0); assert.equal(conversation.contacto_id, 7); const ambiguous = item(minor); const result = await run(ambiguous, '1', { patientModel: { findAll: async () => [] }, contactModel: { findAll: async () => [{ id: 1 }, { id: 2 }] } }); assert.equal(result.responseKind, 'AMBIGUOUS_GUARDIAN'); });
test('cancelar y duplicado no crean datos', async () => { assert.equal((await run(item(adult), '3', {})).responseKind, 'NEW_PATIENT_CANCELLED'); const result = await run(item(adult), '1', { patientModel: { findAll: async () => [{ id: 4 }] } }); assert.equal(result.responseKind, 'POSSIBLE_PATIENT_DUPLICATE'); });
