const { Op } = require('sequelize');
const crypto = require('crypto');
const { Usuario, WhatsappReceptionReferral, WhatsappConversacion } = require('../models');
const notifications = require('./internalNotification.service');
const { getInternalNotificationsEnabled } = require('../config/whatsapp');

const activeUsers = async (roles, userModel = Usuario) => (await userModel.findAll({ where: { rol: { [Op.in]: roles }, estado: 'activo', activo: true }, attributes: ['id'] })).map((item) => Number(item.id));
const messageToken = (value) => crypto.createHash('sha256').update(String(value)).digest('hex');
const safe = async (action) => { if (!getInternalNotificationsEnabled()) return []; try { return await action(); } catch (_) { console.error('[Notifications] Error generando notificación'); return []; } };
const newReferral = async (referral, deps = {}) => safe(async () => { const ids = await activeUsers(['admin', 'personal'], deps.userModel); return (deps.notificationService || notifications).createForUsers({ userIds: ids, type: 'NUEVA_DERIVACION', title: 'Nueva solicitud de recepción', message: 'Existe una nueva derivación pendiente de atención.', entityType: 'DERIVACION_WHATSAPP', entityId: referral.id, referralId: referral.id, priority: 'NORMAL', idempotencyKey: (userId) => `new-referral:${referral.id}:${userId}` }); });
const assignedReferral = async (referral, deps = {}) => safe(async () => (deps.notificationService || notifications).createForUsers({ userIds: [referral.responsable_usuario_id], type: 'DERIVACION_ASIGNADA', title: 'Solicitud asignada', message: 'La derivación quedó asignada a tu usuario.', entityType: 'DERIVACION_WHATSAPP', entityId: referral.id, referralId: referral.id, priority: 'NORMAL', idempotencyKey: (userId) => `assigned:${referral.id}:${userId}` }));
const patientReply = async ({ phone, metaMessageId }, deps = {}) => safe(async () => { const conversationModel = deps.conversationModel || WhatsappConversacion; const conversation = await conversationModel.findOne({ where: { telefono: phone }, order: [['updated_at', 'DESC'], ['id', 'DESC']], attributes: ['id'] }); if (!conversation) return []; const referralModel = deps.referralModel || WhatsappReceptionReferral; const referral = await referralModel.findOne({ where: { conversacion_id: conversation.id, telefono_normalizado: phone, estado: 'EN_ATENCION' }, order: [['tomada_en', 'DESC'], ['id', 'DESC']] }); if (!referral) return []; let ids = referral.responsable_usuario_id ? [Number(referral.responsable_usuario_id)] : []; const valid = ids.length ? await activeUsersForIds(ids, deps.userModel) : []; if (!valid.length) ids = await activeUsers(['admin'], deps.userModel); else ids = valid; const token = messageToken(metaMessageId); return (deps.notificationService || notifications).createForUsers({ userIds: ids, type: 'RESPUESTA_PACIENTE', title: 'Nueva respuesta por WhatsApp', message: 'El contacto respondió a una solicitud que tienes en atención.', entityType: 'DERIVACION_WHATSAPP', entityId: referral.id, referralId: referral.id, priority: 'ALTA', idempotencyKey: (userId) => `patient-reply:${token}:${userId}` }); });
const activeUsersForIds = async (ids, userModel = Usuario) => (await userModel.findAll({ where: { id: { [Op.in]: ids }, estado: 'activo', activo: true }, attributes: ['id'] })).map((item) => Number(item.id));
const manualReplyFailed = async (reply, deps = {}) => safe(async () => { let ids = await activeUsersForIds([Number(reply.usuario_id)], deps.userModel); if (!ids.length) ids = await activeUsers(['admin'], deps.userModel); return (deps.notificationService || notifications).createForUsers({ userIds: ids, type: 'ENVIO_WHATSAPP_FALLIDO', title: 'No se pudo enviar una respuesta', message: 'La respuesta por WhatsApp falló definitivamente. Revisa la derivación.', entityType: 'RESPUESTA_RECEPCION_WHATSAPP', entityId: reply.id, referralId: reply.derivacion_id, replyId: reply.id, priority: 'ALTA', idempotencyKey: (userId) => `manual-failed:${reply.id}:${userId}` }); });

module.exports = { messageToken, activeUsers, activeUsersForIds, newReferral, assignedReferral, patientReply, manualReplyFailed };
