const fs=require('fs');const path=require('path');const {spawnSync}=require('child_process');
const REQUIRED_TABLES=require('./verifyDatabase').required;
const SECRET_KEYS=['DB_PASSWORD','JWT_SECRET','WHATSAPP_ACCESS_TOKEN','WHATSAPP_VERIFY_TOKEN','WHATSAPP_APP_SECRET'];
const bool=(value)=>value==='true';
const inspectEnvironment=(env=process.env)=>{const errors=[],warnings=[];if(env.DB_SYNC!=='false')errors.push('DB_SYNC debe ser false');if(env.NODE_ENV!=='production')warnings.push('NODE_ENV no es production');for(const key of ['DB_HOST','DB_PORT','DB_NAME','DB_USER','JWT_SECRET','CORS_ALLOWED_ORIGINS'])if(!env[key])errors.push(`Falta ${key}`);if((env.JWT_SECRET||'').length<32)errors.push('JWT_SECRET debe tener al menos 32 caracteres');if(bool(env.WHATSAPP_REMINDERS_ENABLED)||bool(env.WHATSAPP_MANUAL_REPLIES_ENABLED)||bool(env.WHATSAPP_REFERRAL_PENDING_ALERT_ENABLED))warnings.push('Hay jobs o envíos sensibles habilitados');if((env.CORS_ALLOWED_ORIGINS||'').includes('*'))errors.push('CORS no puede contener *');return{errors,warnings,secrets:Object.fromEntries(SECRET_KEYS.map(k=>[k,Boolean(env[k])]))}};
const findTool=(name)=>{const direct=spawnSync('where.exe',[name],{encoding:'utf8'});if(direct.status===0)return true;const root='C:\\Program Files\\PostgreSQL';if(!fs.existsSync(root))return false;return fs.readdirSync(root).some(version=>fs.existsSync(path.join(root,version,'bin',`${name}.exe`)))};
const run=async({env=process.env,db=require('../config/database')}={})=>{const report=inspectEnvironment(env);try{await db.authenticate();const [rows]=await db.query("SELECT table_name AS name FROM information_schema.tables WHERE table_schema='public'",{raw:true});const names=new Set(rows.map(x=>x.name));const missing=REQUIRED_TABLES.filter(x=>!names.has(x));if(missing.length)report.errors.push(`Tablas faltantes: ${missing.join(', ')}`)}catch{report.errors.push('No se pudo conectar a PostgreSQL')}for(const tool of ['pg_dump','pg_restore'])if(!findTool(tool))report.errors.push(`No está disponible ${tool}`);const backupDir=path.resolve(__dirname,'../../backups'),writeTarget=fs.existsSync(backupDir)?backupDir:path.dirname(backupDir);try{fs.accessSync(writeTarget,fs.constants.W_OK)}catch{report.errors.push('La carpeta backups no es escribible')}report.configuration={node_env:env.NODE_ENV||'AUSENTE',db_sync:env.DB_SYNC||'AUSENTE',whatsapp_enabled:bool(env.WHATSAPP_ENABLED),reminders_enabled:bool(env.WHATSAPP_REMINDERS_ENABLED),manual_replies_enabled:bool(env.WHATSAPP_MANUAL_REPLIES_ENABLED),referral_alerts_enabled:bool(env.WHATSAPP_REFERRAL_PENDING_ALERT_ENABLED),templates_configured:Boolean(env.WHATSAPP_REMINDER_TEMPLATE_NAME&&env.WHATSAPP_REMINDER_TEMPLATE_LANGUAGE)};report.status=report.errors.length?'NOT_READY':report.warnings.length?'READY_WITH_WARNINGS':'READY';console.log(JSON.stringify(report,null,2));return report};
if(require.main===module)run().catch(()=>{console.error('READINESS_ERROR');process.exitCode=1}).finally(()=>require('../config/database').close());
module.exports={inspectEnvironment,run,SECRET_KEYS};
