const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const CONVERSATION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVA', CANCELLED: 'CANCELADA', FINISHED: 'FINALIZADA', EXPIRED: 'EXPIRADA'
});
const CONVERSATION_STEPS = Object.freeze({
  WAITING_OPTION: 'ESPERANDO_OPCION',
  START_BOOKING: 'INICIO_AGENDAR_CITA',
  START_APPOINTMENTS: 'INICIO_CONSULTAR_CITAS',
  START_RESCHEDULE_CANCEL: 'INICIO_REPROGRAMAR_CANCELAR',
  START_CENTER_INFO: 'INICIO_INFORMACION_CENTRO',
  RECEPTION: 'DERIVACION_RECEPCION',
  WAITING_NAME: 'ESPERANDO_NOMBRE',
  WAITING_REASON: 'ESPERANDO_MOTIVO',
  WAITING_DATE: 'ESPERANDO_FECHA_PREFERIDA',
  WAITING_SHIFT: 'ESPERANDO_TURNO_PREFERIDO',
  WAITING_TIME: 'ESPERANDO_HORA_PREFERIDA',
  WAITING_CONFIRMATION: 'ESPERANDO_CONFIRMACION_SOLICITUD',
  WAITING_EDIT_FIELD: 'ESPERANDO_CAMPO_A_MODIFICAR',
  REQUEST_CREATED: 'SOLICITUD_CREADA',
  SEARCHING_AVAILABILITY: 'BUSCANDO_DISPONIBILIDAD',
  WAITING_SLOT_SELECTION: 'ESPERANDO_SELECCION_HORARIO',
  NO_AVAILABILITY: 'SIN_DISPONIBILIDAD',
  WAITING_NEW_DATE: 'ESPERANDO_NUEVA_FECHA',
  SLOT_SELECTED: 'HORARIO_SELECCIONADO',
  WAITING_FINAL_CONFIRMATION: 'ESPERANDO_CONFIRMACION_FINAL',
  APPOINTMENT_CREATED: 'CITA_CREADA',
  REFERRED_RECEPTION: 'DERIVADA_RECEPCION',
  WAITING_APPOINTMENT_SELECTION: 'ESPERANDO_SELECCION_CITA',
  SHOWING_APPOINTMENT_DETAIL: 'MOSTRANDO_DETALLE_CITA',
  WAITING_APPOINTMENT_ACTION: 'ESPERANDO_ACCION_CITA',
  WAITING_CANCELLATION_CONFIRMATION: 'ESPERANDO_CONFIRMACION_CANCELACION',
  WAITING_RESCHEDULE_DATE: 'ESPERANDO_FECHA_REPROGRAMACION',
  WAITING_RESCHEDULE_SLOT: 'ESPERANDO_HORARIO_REPROGRAMACION',
  WAITING_RESCHEDULE_CONFIRMATION: 'ESPERANDO_CONFIRMACION_REPROGRAMACION',
  APPOINTMENT_CANCELLED: 'CITA_CANCELADA',
  APPOINTMENT_RESCHEDULED: 'CITA_REPROGRAMADA',
  WAITING_REMINDER_RESPONSE: 'ESPERANDO_RESPUESTA_RECORDATORIO',
  WAITING_NONATTENDANCE_CONFIRMATION: 'ESPERANDO_CONFIRMACION_NO_ASISTIRA',
  ATTENDANCE_CONFIRMED: 'ASISTENCIA_CONFIRMADA',
  REMINDER_REFERRED_RECEPTION: 'RECORDATORIO_DERIVADO_RECEPCION'
});
const MAIN_OPTIONS = Object.freeze({
  BOOK: 'AGENDAR_CITA', APPOINTMENTS: 'CONSULTAR_CITAS',
  RESCHEDULE_CANCEL: 'REPROGRAMAR_CANCELAR', CENTER_INFO: 'INFORMACION_CENTRO',
  RECEPTION: 'HABLAR_RECEPCION'
});
const CONTACT_TYPES = Object.freeze({ EXISTING: 'PACIENTE_EXISTENTE', NEW: 'CONTACTO_NUEVO' });

const WhatsappConversacion = sequelize.define('WhatsappConversacion', {
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true, allowNull: false },
  telefono: { type: DataTypes.STRING(15), allowNull: false },
  paciente_id: { type: DataTypes.INTEGER, allowNull: true },
  tipo_contacto: { type: DataTypes.STRING(30), allowNull: false, validate: { isIn: [Object.values(CONTACT_TYPES)] } },
  estado: { type: DataTypes.STRING(15), allowNull: false, defaultValue: CONVERSATION_STATUS.ACTIVE, validate: { isIn: [Object.values(CONVERSATION_STATUS)] } },
  paso_actual: { type: DataTypes.STRING(50), allowNull: false, defaultValue: CONVERSATION_STEPS.WAITING_OPTION, validate: { isIn: [Object.values(CONVERSATION_STEPS)] } },
  opcion_principal: { type: DataTypes.STRING(40), allowNull: true, validate: { isIn: [[...Object.values(MAIN_OPTIONS), null]] } },
  contexto: { type: DataTypes.JSONB, allowNull: false, defaultValue: {} },
  ultimo_mensaje_en: { type: DataTypes.DATE, allowNull: false },
  expira_en: { type: DataTypes.DATE, allowNull: false }
}, {
  tableName: 'whatsapp_conversaciones', timestamps: true,
  createdAt: 'created_at', updatedAt: 'updated_at'
});

module.exports = { WhatsappConversacion, CONVERSATION_STATUS, CONVERSATION_STEPS, MAIN_OPTIONS, CONTACT_TYPES };
