ALTER TABLE pacientes
  ADD COLUMN IF NOT EXISTS lugar_nacimiento VARCHAR(150),
  ADD COLUMN IF NOT EXISTS peso DECIMAL(5, 2),
  ADD COLUMN IF NOT EXISTS talla DECIMAL(5, 2),
  ADD COLUMN IF NOT EXISTS imc DECIMAL(5, 2);
