BEGIN;

ALTER TABLE whatsapp_conversaciones
  DROP CONSTRAINT IF EXISTS whatsapp_conversaciones_paso_check;

ALTER TABLE whatsapp_conversaciones
  ADD CONSTRAINT whatsapp_conversaciones_paso_check CHECK (paso_actual IN (
    'ESPERANDO_OPCION', 'INICIO_AGENDAR_CITA', 'INICIO_CONSULTAR_CITAS',
    'INICIO_REPROGRAMAR_CANCELAR', 'INICIO_INFORMACION_CENTRO', 'DERIVACION_RECEPCION',
    'ESPERANDO_NOMBRE', 'ESPERANDO_MOTIVO', 'ESPERANDO_FECHA_PREFERIDA',
    'ESPERANDO_TURNO_PREFERIDO', 'ESPERANDO_HORA_PREFERIDA',
    'ESPERANDO_CONFIRMACION_SOLICITUD', 'ESPERANDO_CAMPO_A_MODIFICAR', 'SOLICITUD_CREADA',
    'BUSCANDO_DISPONIBILIDAD', 'ESPERANDO_SELECCION_HORARIO', 'SIN_DISPONIBILIDAD',
    'ESPERANDO_NUEVA_FECHA', 'HORARIO_SELECCIONADO'
  ));

COMMIT;
